blank_issues_enabled: false
contact_links:
  - name: Como contribuir
    url: https://github.com/Heazts/redacoes-nota-1000-enem-2025/blob/main/CONTRIBUTING.md
    about: Antes de abrir uma issue em branco, confira os critérios de inclusão, correção e remoção em CONTRIBUTING.md.
